export const tableOrderColumnStructure = [
  {
    col_name: 'expand',
    col_visible: true,
    col_label: '>',
    col_type: 'symbol',
    col_value: ['fnExpand', 'expand'],
    col_subValue: null,
    col_width: 3,
    col_minWidth: 10,
    col_sort: null,
  },
  {
    col_name: 'id',
    col_visible: false,
    col_label: 'ID',
    col_type: 'string',
    col_value: null,
    col_subValue: null,
    col_width: 20,
    col_minWidth: 5,
    col_sort: null,
  },
  {
    col_name: 'orderId',
    col_visible: true,
    col_label: 'Order ID',
    col_type: 'string',
    col_value: ['fnLinkOrderIDValue', 'orderId'],
    col_subValue: ['fnTestStringValue', 'noOfSchedules', 'orderId'],
    col_width: 15,
    col_minWidth: 150,
    col_sort: null,
  },
  {
    col_name: 'govtRoNo',
    col_visible: true,
    col_label: 'Govt. RO No.',
    col_type: 'string',
    col_value: ['fnStringValue', 'govtRoNo'],
    col_subValue: null,
    col_width: 10,
    col_minWidth: 80,
    col_sort: 'asc',
  },
  {
    col_name: 'noOfSchedules',
    col_visible: true,
    col_label: 'Schedule\nCount',
    col_type: 'string',
    col_value: ['fnNumIntValue', 'noOfSchedules'],
    col_subValue: null,
    col_width: 9,
    col_minWidth: 80,
    col_sort: 'asc',
  },
  {
    col_name: 'spotsMaximum',
    col_visible: true,
    col_label: 'Spots\nMaximum',
    col_type: 'string',
    col_value: ['fnNumIntValue', 'spotsMaximum'],
    col_subValue: null,
    col_width: 9,
    col_minWidth: 80,
    col_sort: 'asc',
  },
  {
    col_name: 'spotsScheduled',
    col_visible: true,
    col_label: 'Spots\nScheduled',
    col_type: 'string',
    col_value: ['fnNumIntValue', 'spotsScheduled'],
    col_subValue: null,
    col_width: 9,
    col_minWidth: 80,
    col_sort: 'asc',
  },
  {
    col_name: 'spotsPossible',
    col_visible: true,
    col_label: 'Spots\nMovies',
    col_type: 'string',
    col_value: ['fnNumIntValue', 'spotsPossible'],
    col_subValue: null,
    col_width: 9,
    col_minWidth: 80,
    col_sort: 'asc',
  },
  {
    col_name: 'spotsPlayed',
    col_visible: true,
    col_label: 'Spots\nPlayed',
    col_type: 'string',
    col_value: ['fnNumIntValue', 'spotsPlayed'],
    col_subValue: null,
    col_width: 9,
    col_minWidth: 80,
    col_sort: 'asc',
  },
  {
    col_name: 'takenPercent',
    col_visible: true,
    col_label: 'Taken\nPercent',
    col_type: 'string',
    col_value: ['fnNumIntValue', 'takenPercent'],
    col_subValue: null,
    col_width: 9,
    col_minWidth: 80,
    col_sort: 'asc',
  },
  {
    col_name: 'playedPercent',
    col_visible: true,
    col_label: 'Played\nPercent',
    col_type: 'string',
    col_value: ['fnNumIntValue', 'playedPercent'],
    col_subValue: null,
    col_width: 9,
    col_minWidth: 80,
    col_sort: 'asc',
  },
  {
    col_name: 'spotsPlayedPercent',
    col_visible: true,
    col_label: 'Spots\nPercent',
    col_type: 'string',
    col_value: ['fnNumIntValue', 'spotsPlayedPercent'],
    col_subValue: null,
    col_width: 9,
    col_minWidth: 80,
    col_sort: 'asc',
  },
];

export const tableSchedulesColumnStructure = [
  {
    col_name: 'expand',
    col_visible: true,
    col_label: '>',
    col_type: 'symbol',
    col_value: ['fnExpand', 'expand'],
    col_subValue: null,
    col_width: 3,
    col_minWidth: 10,
    col_sort: null,
  },
  {
    col_name: 'scheduleId',
    col_visible: true,
    col_label: 'Schedule Name',
    col_type: 'string',
    col_value: ['fnScheduleNameValue', 'scheduleId', 'name'],
    col_subValue: ['fnStringValue', 'scheduleId'],
    col_width: 25,
    col_minWidth: 150,
    col_sort: null,
  },
  {
    col_name: 'noOfScreens',
    col_visible: true,
    col_label: 'Screen\nCount',
    col_type: 'string',
    col_value: ['fnStringValue', 'noOfScreens'],
    col_subValue: null,
    col_width: 9,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'totalTaken',
    col_visible: true,
    col_label: 'Taken\nCount',
    col_type: 'string',
    col_value: ['fnTakenCountValue', 'totalTaken'],
    col_subValue: ['fnNotTakenCountValue', 'totalNotTaken'],
    col_width: 9,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'totalPlayed',
    col_visible: true,
    col_label: 'Played\nCount',
    col_type: 'string',
    col_value: ['fnPlayedCountValue', 'totalPlayed'],
    col_subValue: ['fnNotPlayedCountValue', 'totalNotPlayed'],
    col_width: 9,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'spotsMaximum',
    col_visible: true,
    col_label: 'Spots\nMax/Sch.',
    col_type: 'string',
    col_value: ['fnSpotsMaxValue', 'spotsMaximum'],
    col_subValue: ['fnSpotsScheduledValue', 'spotsScheduled'],
    col_width: 9,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'spotsPossible',
    col_visible: true,
    col_label: 'Spots\nMov./Play',
    col_type: 'string',
    col_value: ['fnSpotsMovValue', 'spotsPossible'],
    col_subValue: ['fnSpotsPlayedValue', 'spotsPlayed'],
    col_width: 9,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'takenPercent',
    col_visible: true,
    col_label: 'Taken\nPercent',
    col_type: 'string',
    col_value: ['fnNumNotIntValue', 'takenPercent'],
    col_subValue: null,
    col_width: 9,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'playedPercent',
    col_visible: true,
    col_label: 'Played\nPercent',
    col_type: 'string',
    col_value: ['fnNumNotIntValue', 'playedPercent'],
    col_subValue: null,
    col_width: 9,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'spotsPlayedPercent',
    col_visible: true,
    col_label: 'Spots\nPercent',
    col_type: 'string',
    col_value: ['fnNumNotIntValue', 'spotsPlayedPercent'],
    col_subValue: null,
    col_width: 9,
    col_minWidth: 100,
    col_sort: 'asc',
  },
];

export const tableScreensColumnStructure = [
  {
    col_name: 'expand',
    col_visible: true,
    col_label: '>',
    col_type: 'symbol',
    col_value: ['fnExpand', 'expand'],
    col_subValue: null,
    col_width: 3,
    col_minWidth: 10,
    col_sort: null,
  },
  {
    col_name: 'screen',
    col_visible: true,
    col_label: 'Screen Name',
    col_type: 'string',
    col_value: ['fnScreenNameValue', 'screen', 'screenId'],
    col_subValue: ['fnScreenCodeValue', 'screenCode'],
    col_width: 20,
    col_minWidth: 150,
    col_sort: null,
  },
  {
    col_name: 'scheduleStatus',
    col_visible: true,
    col_label: 'Schedule\nStatus',
    col_type: 'string',
    col_value: ['fnStringValue', 'scheduleStatus'],
    col_subValue: ['fnScreenDateValue', 'takenOn'],
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'playLogStatus',
    col_visible: true,
    col_label: 'Playlog\nStatus',
    col_type: 'string',
    col_value: ['fnStringValue', 'playLogStatus'],
    col_subValue: ['fnScreenDateValue', 'lastPlayedOn'],
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'spotsMaximum',
    col_visible: true,
    col_label: 'Spots\nMaximum',
    col_type: 'string',
    col_value: ['fnNumIntValue', 'spotsMaximum'],
    col_subValue: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'spotsScheduled',
    col_visible: true,
    col_label: 'Spots\nScheduled',
    col_type: 'string',
    col_value: ['fnNumIntValue', 'spotsScheduled'],
    col_subValue: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'spotsPossible',
    col_visible: true,
    col_label: 'Spots\nMovies',
    col_type: 'string',
    col_value: ['fnNumIntValue', 'spotsPossible'],
    col_subValue: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'spotsPlayed',
    col_visible: true,
    col_label: 'Spots\nPlayed',
    col_type: 'string',
    col_value: ['fnStringValue', 'spotsPlayed'],
    col_subValue: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'spotsPlayedPercent',
    col_visible: true,
    col_label: 'Spots\nPercent',
    col_type: 'string',
    col_value: ['fnNumIntValue', 'spotsPlayedPercent'],
    col_subValue: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'asc',
  },
];

export const tableShowsColumnStructure = [
  {
    col_name: 'showDate',
    col_visible: true,
    col_label: 'Date',
    col_type: 'string',
    col_value: ['fnStringValue', 'showDate'],
    col_subValue: null,
    col_width: 12,
    col_minWidth: 150,
    col_sort: null,
  },
  {
    col_name: 'startTime',
    col_visible: true,
    col_label: 'Time',
    col_type: 'string',
    col_value: ['fnTimeValue', 'startTime', 'endTime'],
    col_subValue: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'position',
    col_visible: true,
    col_label: 'Position',
    col_type: 'string',
    col_value: ['fnStringValue', 'position'],
    col_subValue: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'prefPosition',
    col_visible: true,
    col_label: 'Pref.\nPosition',
    col_type: 'string',
    col_value: ['fnStringValue', 'prefPosition'],
    col_subValue: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'moviesPlayed',
    col_visible: true,
    col_label: 'Movie\nPlayed',
    col_type: 'string',
    col_value: ['fnStringValue', 'moviesPlayed'],
    col_subValue: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'spotRepetition',
    col_visible: true,
    col_label: 'Repetition',
    col_type: 'string',
    col_value: ['fnStringValue', 'spotRepetition'],
    col_subValue: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'spotsScheduled',
    col_visible: true,
    col_label: 'Spots\nScheduled',
    col_type: 'string',
    col_value: ['fnNumIntValue', 'spotsScheduled'],
    col_subValue: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'spotsPlayed',
    col_visible: true,
    col_label: 'Spots\nPlayed',
    col_type: 'string',
    col_value: ['fnStringValue', 'spotsPlayed'],
    col_subValue: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'asc',
  },
  {
    col_name: 'spotsPlayedPercent',
    col_visible: true,
    col_label: 'Spots\nPercent',
    col_type: 'string',
    col_value: ['fnNumNotIntValue', 'spotsPlayedPercent'],
    col_subValue: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'asc',
  },
];

export const summeryCardStructure = [
  {
    className: 'activeIcon',
    response: 'noOfActive',
    label: 'Planned',
  },
  {
    className: 'pausedIcon',
    response: 'noOfProblematic',
    label: 'Logs Pending',
  },
  {
    className: 'consumedIcon',
    response: 'noOfProblematic',
    label: 'Problematic',
  },
  {
    className: 'completedIcon',
    response: 'noOfCompleted',
    label: 'Completed',
  },
  {
    className: 'expiredIcon',
    response: 'noOfUnoptimized',
    label: 'Expired',
  },
  {
    className: 'plannedIcon',
    response: 'noOfPlaned',
    label: 'Planned',
  },
  {
    className: 'draftIcon',
    response: 'problematicPercent',
    label: 'Problematic %',
  },
];
